### ISSUE TITLE
Shipment Discounts Double Counted in Solidus 2.4

### ISSUE THREAD

**Issue by joshhepworth** [boomerdigital/solidus_avatax_certified#107]
We're seeing this issue in Solidus 2.4, but it may exist in other versions as well.

## Reproduction Steps

1. Configure a flat rate shipping rate for any number larger than $0.
2. Add a promotion that automatically applies and makes all shipments on an order free.
3. Place an order.
4. The tax will be calculated as if the subtotal is: `(subtotal) + (shipment cost - discounts) - (all discounts, including shipment discounts)`

I think that's related to this line:

https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/solidus_avatax_certified/line.rb#L61

Which is the `(shipment cost - discounts)`.

and this line:

https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/solidus_avatax_certified/request/get_tax.rb#L9

Which includes order adjustments _and_ shipment adjustments.

I _think_ the best way to handle this will be to exclude shipment adjustments from the line in `get_tax.rb`. However, there may be better ways to handle this in the Avatax API that I am not aware of. My assumption is based on assuming that when we offer free shipping we want to make sure the shipment total is $0 to make sure that tax is not calculated against this value.

**Comment by joshhepworth** [comment]
Is there anything else I can provide to assist in resolving this issue?

**Comment by joshhepworth** [comment]
Is this an issue that we can expect to be addressed in an update?

**Comment by dhonig** [comment]
We have a big push this week on a release but should be able to put in some
maintenance cycles soon.

**Comment by HuckThom** [comment]
@dhonig @acreilly @jmamap1 - Are there any updates here? Thanks!

**Comment by acreilly** [comment]
Thank you, the update has been fixed here: https://github.com/boomerdigital/solidus_avatax_certified/pull/111
