### ISSUE TITLE
VCR cassettes not up to date

### ISSUE THREAD

**Issue by BravoSimone** [boomerdigital/solidus_avatax_certified#108]
I'm trying to refresh this gem's cassettes locally (using our customer's account), in the response I always get `"nonTaxable":20.0` and I can't get a taxable amount greater than zero. I'm using the same avatax account successfully in the development environment.

Also, what do you think about using VCR's [filter_sensitive_data](https://relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/filter-sensitive-data) allowing other developers to compare requests/responses easily?

**Comment by BravoSimone** [comment]
After some research, it looks like Alabama is almost tax-free. Using a shipping address from New York I can get a tax greater than zero. I'm opening a PR to fix all the points listed above.

**Comment by acreilly** [comment]
Updated VCR cassettes here: https://github.com/boomerdigital/solidus_avatax_certified/pull/111
