### ISSUE TITLE
Merge setup.md and readme.md?

### ISSUE THREAD

**Issue by aldesantis** [boomerdigital/solidus_avatax_certified#118]
Is there a reason for these two to be separated or can we merge them together? It seems like readme.md is a much better place to describe setup instructions.

**Comment by dhonig** [comment]
@aldesantis  thanks for your contributions here.  I think the reason we have it in the wiki is the size of the content and our desire to provide detailed screenshots.  I suppose it comes down to a matter of opinion but I think the README.md should provide the general overview and then child pages can provide deeper information.  So I'm in favor of keeping it the way it is.

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_avatax_certified/pull/119
