### ISSUE TITLE
1.3 Progress?

### ISSUE THREAD

**Issue by ericsaupe** [boomerdigital/solidus_avatax_certified#14]
Hey everyone,

I saw 1.2 was certified by Avalara, congrats 🎉! Any update on the 1.3 branch? I see there is one for solidus 1.3 and I was just wondering about an update for when we can start using it in our solidus 1.3 application.

Thanks!

**Comment by dhonig** [comment]
cc: @acreilly

**Comment by acreilly** [comment]
Hey, @ericsaupe. Getting there. Although we were certified, Avalara asked for a few extra features to be done on v1.2, once I complete those I will get them into v1.3 and test. I should have v1.3 complete by the end of this week.

**Comment by acreilly** [comment]
Here you go @ericsaupe ! https://github.com/boomerdigital/solidus_avatax_certified/tree/v1.3
