### ISSUE TITLE
Javascript not formatted correctly

### ISSUE THREAD

**Issue by ericsaupe** [boomerdigital/solidus_avatax_certified#19]
We tried to deploy using the installed javascript to our production servers and got `V8::Error: SyntaxError: Unexpected token: operator (>)` when we tried to compile the assets. After removing the solidus_avatax_certified javascript from our project all was well again. I ran some of the JS files through jslint.com and it came up with a number of errors. Looks to only be a problem on Ubuntu since our local OSX machines weren't picking it up.

**Comment by acreilly** [comment]
Hm, ok. I ran the JS files through JSLint and made the changes I could. Maybe this will fix your issue?
https://github.com/boomerdigital/solidus_avatax_certified/pull/23

**Comment by ericsaupe** [comment]
It may, only way is to try a deploy again. I'll try it tomorrow

**Comment by ericsaupe** [comment]
It didn't seem to fix it. Same error.

**Comment by acreilly** [comment]
Double checking, did you checkout to that branch? I didn't merge it yet

**Comment by acreilly** [comment]
Got it! Take a look at PR #23 again

**Comment by acreilly** [comment]
@ericsaupe Did this solve your issue?
