### ISSUE TITLE
Can't edit credentials in Admin without an Address

### ISSUE THREAD

**Issue by ericsaupe** [boomerdigital/solidus_avatax_certified#20]
After running the `PreferenceSeeder` I tried to edit credentials in the Spree Admin but was met with a 500. I had to run `Spree::AvalaraPreference.origin_address.update(value: {"Country": "US", "Region": "UT"}.to_json)` to get there.

**Comment by acreilly** [comment]
I'm not running into this error, can you post the logs?

**Comment by ericsaupe** [comment]
I think how I did it was to run `PreferenceSeeder` without any environment variables which sets `origin_address - {}`. Then in the view for the edit settings it tries to access a key in that hash that doesn't exist and throws the error.

**Comment by acreilly** [comment]
Ah, ok. I see what you mean. Here: https://github.com/boomerdigital/solidus_avatax_certified/pull/24
