### ISSUE TITLE
Solidus 2.0 and Rails 5

### ISSUE THREAD

**Issue by ericsaupe** [boomerdigital/solidus_avatax_certified#29]
The Solidus core team is updating all of their core gems because Solidus 2.0 with support for Rails 5 is on the horizon. In addition to that they have a pre-release for 1.4. Are you guys going to support these versions as well?

**Comment by acreilly** [comment]
Yes. I haven't been following the updates, but just give me a heads up when a new stable version comes out and I'll get working on it.

**Comment by ericsaupe** [comment]
The beta is out now and they are already updating their gems to be compatible.

https://github.com/solidusio/solidus/releases

https://github.com/solidusio/solidus_auth_devise/pull/72
https://github.com/solidusio/solidus_braintree/pull/51

**Comment by ericsaupe** [comment]
@acreilly they have released 1.4 and 2.0

**Comment by acreilly** [comment]
Ah, I was not aware of 1.4. There is a v2.0 branch

**Comment by ericsaupe** [comment]
1.4 is the same as 2.0 but relies on Rails 4.2

**Comment by skukx** [comment]
@acreilly The v2.0 branch currently relies on solidus 2.0.0.rc1.  The solidus version should be updated to rely on solidus 2.0.0

**Comment by acreilly** [comment]
Our v2.0 version is actually not complete. Will let you know when it is.

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_avatax_certified/pull/36
@ericsaupe @mtomov @skukx Would you mind reviewing?

**Comment by acreilly** [comment]
On master
