### ISSUE TITLE
Single Version

### ISSUE THREAD

**Issue by ericsaupe** [boomerdigital/solidus_avatax_certified#35]
The Solidus extensions have one version that works across all versions of Solidus. This would clean up the many branches and make the project easier to manage. Examples: https://github.com/solidusio/solidus_braintree, https://github.com/solidusio/solidus_gateway.

View of all extensions and compatability with the current version of each gem http://extensions.solidus.io/

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_avatax_certified/pull/36

**Comment by acreilly** [comment]
On master
