### ISSUE TITLE
Previous Tax Amount when recalculated to 0

### ISSUE THREAD

**Issue by ericsaupe** [boomerdigital/solidus_avatax_certified#43]
Why is `prev_tax_amount` returned if the `avalara_response[:TotalTax]` is 0? Shouldn't it respect that new calculation?

The use case we have is we get to the payment step, taxes are calculated.
A promotion is applied, making the promo total the price of the item, and taxes are recalculated.
The recalculated tax is 0 but it instead keeps the old tax amount calculated previously.

**Comment by acreilly** [comment]
Good point, I will get to that this week.

**Comment by acreilly** [comment]
Ah, the reason why we did this was in the case that it errors out. At the moment, if there is an error with tax calculation, it returns 0.00. Do you have a suggestion on what to do in case on an error?

This has been something I have been meaning to get to but need opinions from others on how to handle the situation. Do we prevent the user from being able to check out? Do we use the previous amount that was calculated? Do we just give them 0 tax? Thoughts?

**Comment by ericsaupe** [comment]
Doesn't the response come back with some sort of `error` key? Is there another way, other than the 0.00 return, to see that the response was an error?

**Comment by acreilly** [comment]
I think that was the original developers idea. https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/spree/avalara_transaction.rb#L101
There is a more detailed error message beforehand: https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/tax_svc.rb#L18

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_avatax_certified/pull/44
