### ISSUE TITLE
Previous Versions No Longer Available

### ISSUE THREAD

**Issue by thejbsmith** [boomerdigital/solidus_avatax_certified#50]
I've been developing a site using Solidus 1.4.1, which was also using the solidus_avatax_certified gem on the same branch. Today I made a PR and noticed that my Travis build failed. It failed when trying to do a git reset on the cache for solidus_avatax_certified.

Taking a closer look at the repo, it appears that the branches for previous versions have been removed, even though the wiki states to reference the branch in the installation instructions. It doesn't look like the gem is distributed anywhere, this is causing issues for me since there doesn't seem to be a good way to access older versions of the gem.

Was this done intentionally? What is the best way for me to go about continuing to use this gem? Is there any chance of actually getting the gem on RubyGems where users could just reference any version of the gem that they need?

Thanks, any help is appreciated.

**Comment by acreilly** [comment]
All solidus versions <= 2.0 work with master. I would suggest setting up in your Gemfile to use the master branch of this gem.

**Comment by thejbsmith** [comment]
@acreilly, thanks for the reply.

What happens when master changes though? Without a way to clearly distinguish a version that we know will not change or be removed, it leaves that app brittle.

For now we have forked the repo in order for us to have something that we can control.

Are there any plans on releasing this through RubyGems? Or is it going to be left as is?

**Comment by acreilly** [comment]
Master is stable so I just released master to rubygems. I set the version to 1.0.0. https://rubygems.org/gems/solidus_avatax_certified

Hope that helps

**Comment by thejbsmith** [comment]
Awesome! Thanks!

**Comment by dhonig** [comment]
@thejbsmith feel free to send us feedback.  We're here to help, but don't always know what folks need!

**Comment by thejbsmith** [comment]
@dhonig, will do. Getting this into RubyGems was great, and all I needed. @acreilly was great responding to my issue, and getting it up on RubyGems within a few hours of me asking.
