### ISSUE TITLE
Multiple Payments

### ISSUE THREAD

**Issue by skukx** [boomerdigital/solidus_avatax_certified#51]
https://github.com/boomerdigital/solidus_avatax_certified/blob/7626631802a5550d09b29e42c5f8f3ba52fdef65/app/models/spree/payment_decorator.rb#L17

When there are multiple payments on an order (Credit Card, Gift Card). This line will mess up checkout by changing the actual amount on the payment, to the order total.
For example:
Order total is $19

1st Payment is $10 (gift card)
2nd Payment is $9 (credit card)

See https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order/payments.rb#L42 for below context.

1st Payment: 
  - `process!` then `purchase!` is called
  - $10 captured on first payment
  - `payment.complete!` called
  - oops, `payment.amount` now $19

Now 2nd payment is getting processed:
   - `payment_total` reflects `total` we `break` which causes checkout to fail
   - Customer goes through checkout again
   - Completed payment shows for $19
   - Complete order and all is well even though customer was only actually charged $10

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_avatax_certified/pull/60

**Comment by acreilly** [comment]
@skukx Is this issue been taken care of?

**Comment by skukx** [comment]
Yes I believe so
