### ISSUE TITLE
Errors Being Ignored

### ISSUE THREAD

**Issue by skukx** [boomerdigital/solidus_avatax_certified#53]
Errors returned from Avatax are being ignored.

See: https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/tax_svc.rb#L23
See: https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/spree/avalara_transaction.rb#L101

This isn't very good practice to swipe errors under the rug. At the least the logger should use `warn` instead of `debug` and `info`.  Ignoring these errors could potentially lose a company money by not charging the correct taxes.  Another idea could be created an `avalara_events` table which keeps track of all the avatax events.  So if `#get_tax` fails, `order.avalara_events` would show the response returned from avalara.

In my opinion, custom error classes should be created and allowed to bubble to the application so that the application can handle to error. Or possibly provide a callback the application can tie into so that the application has a choice on what to do about the error.

**Comment by dhonig** [comment]
I'm not a fan of errors being ignored.   I think different stores may want to handle this differently.  Is @skukx what do you think the idea of having a setting "propagate_errors" in the configuration.
 For those who wish to trap the error further up and handle it this would enable it.

**Comment by skukx** [comment]
@dhonig I think that is good, what if an application could register a callback?

```
Spree::Order.class_eval do
    on_tax_error :handle_tax_error

    def handle_tax_error(tax_data, error); end
end
```

**Comment by dhonig** [comment]
@skukx I like the callback idea.  Let's do it.   As for high availability, we shouldn't pass over this one too quickly, but I agree that I don't think we have it dialed in yet.....We should consult with Avalara directly and implement failover patterns as to their recommendation...Which as far as  I remember is not too different from what you suggested.   I know of at least one store that does this today.  Should I work on getting updated guidelines from them and then we can tackle failover and ha as a seperate issue?

**Comment by skukx** [comment]
Yeah, that sounds great

**Comment by acreilly** [comment]
I set up basic error handling for API responses with a ResultCode that is not 'Success', please review: https://github.com/boomerdigital/solidus_avatax_certified/pull/59/files

**Comment by skukx** [comment]
I'll look at it as soon as I get chance, Thanks!

![bitmoji](https://render.bitstrips.com/v2/cpanel/7933842-228647270_8-s1-v1.png?transparent=1&palette=1&width=246)
