### ISSUE TITLE
Avatax REST API V2

### ISSUE THREAD

**Issue by acreilly** [boomerdigital/solidus_avatax_certified#58]
Upgrade gem to utilize Avatax's V2 API.
https://developer.avalara.com/avatax/api-reference/tax/v2/

*V2 API allows adjustments after commit.

**Comment by skukx** [comment]
@acreilly Would you be interested in collaborating on a client for this. This gem would then require the client gem and use it to make the requests.

This would help separate Solidus logic with Avatax logic.  If not no biggie.  I started on an [avatax client](https://github.com/skukx/avatax) about a week ago.  I want to make a few changes such as getting rid of the class variables `@@` and replacing them with class instance variables.

**Comment by acreilly** [comment]
Sounds like a good idea. I will have to fork the client gem though. My concern is that once we have it set up here, if someone makes a change to the client gem and I am unaware, it can affect this one.
