### ISSUE TITLE
Support Solidus 2.1

### ISSUE THREAD

**Issue by skukx** [boomerdigital/solidus_avatax_certified#63]
No support for solidus 2.1 yet
https://github.com/boomerdigital/solidus_avatax_certified/blob/master/solidus_avatax_certified.gemspec#L21

**Comment by acreilly** [comment]
Since there are too many differences when it comes to tax on 2.1, it needs to be on its own branch.
https://github.com/boomerdigital/solidus_avatax_certified/tree/v2.1

**Comment by skukx** [comment]
Is the `v2.1` branch stable?

**Comment by acreilly** [comment]
Yup!
