### ISSUE TITLE
response object is nil in address validation

### ISSUE THREAD

**Issue by ericsaupe** [boomerdigital/solidus_avatax_certified#64]
If there is a problem with the request object in address validation the request object is nil and is still trying to be used later on. https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/tax_svc.rb#L68

**Comment by acreilly** [comment]
Could you send me your logs displaying this error?

**Comment by acreilly** [comment]
Also, what kind of problem in the request? I just set up a request with an address missing Line1 and PostalCode, it returns as expected.

**Comment by acreilly** [comment]
@ericsaupe Is this still an issue?

**Comment by ericsaupe** [comment]
I don't think we've seen it since we first saw the error occur. It is still a possibility simply due to how it is written. If the block above is rescued the `request` variable will be `nil` making the line I linked cause the error. So the exact circumstances to recreate the error I'm not sure about but it would simply be whatever makes the `rescue` trigger.
