### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by acreilly** [boomerdigital/solidus_avatax_certified#65]
Awhile back I was told that Solidus was looking into removing Spree::Preferences in the future, that is why I created Spree::AvalaraPreference. I was misinformed and they will not be removing it.

I would like to go back to using Spree::Preferences rather than holding them in the database.

**Comment by ericsaupe** [comment]
We would like this as well!

**Comment by acreilly** [comment]
@ericsaupe Could you review? https://github.com/boomerdigital/solidus_avatax_certified/pull/67
