### ISSUE TITLE
Universal Branch

### ISSUE THREAD

**Issue by acreilly** [boomerdigital/solidus_avatax_certified#66]
I like how Solidus gems have the master branch work for all versions. In Solidus v2.1, there were some significant changes to tax, where the only way I could think of making it work was to either bring over all that new code, or just put v2.1 on a new branch.

v2.2 just came out and it appears that it will work fine on the v2.1 branch, but I wanted opinions on how I should handle this, maybe find a better solution. Ideally it would be great to get it all on one branch.

@ericsaupe @skukx @jasonfb @dhonig

**Comment by skukx** [comment]
I really like how solidus_paypal_braintree has been setup
https://github.com/solidusio/solidus_paypal_braintree/blob/master/Gemfile

**Comment by acreilly** [comment]
The Gemfile here is very similar: https://github.com/boomerdigital/solidus_avatax_certified/blob/master/Gemfile

The changes are within the solidus code, like the tax helpers that are used now, order adjuster etc
https://github.com/boomerdigital/solidus_avatax_certified/compare/v2.1

**Comment by acreilly** [comment]
BTW that compare isn't accurate.. not sure why it is comparing to an older version of master. But you can see some of the differences

**Comment by skukx** [comment]
I guess it would be nice to be able to see what solidus versions are compatible with each release

**Comment by ericsaupe** [comment]
Spree used to do that with version branches. Solidus seems to prefer extensions to work universally.

**Comment by acreilly** [comment]
I prefer the extensions to work universally because it is MUCH easier to maintain. My concern with v2.1 and up is that the changes are significant enough, in order for me to do that I would have to bring over decent amount of code from solidus.

Are there any ideas on easy ways to do this without overriding too much code?

**Comment by skukx** [comment]
I think the best way to stay universal is to have releases (Tags).  Keep a change log over each release which specifies the solidus versions it is compatible with as well as any other changes.  This way, users can choose the release based on their solidus version. They can choose to upgrade to a new release, or stay on their current release.

**Comment by ericsaupe** [comment]
That way people can lock versions in their Gemfiles for specific releases.

**Comment by jasonfb** [comment]
I would recommend tagging with versions that are either matching Solidus versions or in lock-step with Solidus versions. (by lock-step, I mean, say if this gem's version 3 works for Solidus 1.2-1.4, but then you need to bump to version 4 for Solidus v 2.0, and again to version 5 for Solidus 2.1, etc)

A simple chart on the README (front page) could make it easy to figure out which tag of the gem you want to install corresponding to which version of Solidus.

it seems like trying to achieve universal versioning — where 'master' can be used against any version of Solidus— might work temporarily but won't in the long run.

**Comment by ericsaupe** [comment]
Based on jhawthorn's talk at SolidusConf it seems like this is the proper way to test them against all supported versions of Solidus. Obviously changing to only test against versions we really care about:
https://github.com/solidusio/solidus_auth_devise/blob/master/.travis.yml
https://github.com/solidusio/solidus_auth_devise/blob/master/Gemfile#L3-L4

I don't think it's a bad idea to have a single release that supports sort of the "newer" versions of Solidus. Maybe branches or tags for the older versions?

**Comment by acreilly** [comment]
That is how it was until v2.1. I would love to be able to just have one branch, but the changes from v2.1 are different enough where it makes it incompatible with the older versions. It may be possible to check the version on the changes... but I feel like it would appear hacky.

**Comment by ericsaupe** [comment]
Maybe going forward that is all that is supported by the single release then, 2.1+ because of the major changes to taxes. I'd be cool with that.

**Comment by acreilly** [comment]
Yeah, that would be nice but if you see solidus 2.3, the changes for taxes are large again. https://github.com/solidusio/solidus/pull/1851/files

**Comment by ericsaupe** [comment]
🤦‍♂️ OK, maybe it just won't work since they keep making so many changes to taxes

**Comment by acreilly** [comment]
For Solidus 2.3, it will definitely need to be on a separate branch.

I would love to be able to get 2.2 an below all on one branch though. I am still brainstorming ideas on how to go about this. 

One idea would be to check the current solidus version, and if it is 2.0 or lower, do not load in SolidusAvataxCertified::OrderAdjuster file. Do you think that is possible? There would be a few other tweaks needed to be made, but that is my biggest blocker.
