### ISSUE TITLE
Error in #tax_included_in_price?

### ISSUE THREAD

**Issue by skukx** [boomerdigital/solidus_avatax_certified#76]
https://github.com/boomerdigital/solidus_avatax_certified/blob/29f9eb62c94e7554c0d61e687d725b1e57eeadc9/app/models/solidus_avatax_certified/line.rb#L138

```ruby
 def tax_included_in_price?(item)
   rates_for_item(item).try(:first).included_in_price || false
 end
```

Should be changed to

```ruby
 def tax_included_in_price?(item)
   !!rates_for_item(item).try(:first)&.included_in_price
 end
```

It is possible for the `try` to fail resulting in a `nil` object which will cause an error when trying to call the method `included_in_price`

**Comment by acreilly** [comment]
I should have this change up by the beginning of next week.

**Comment by acreilly** [comment]
Sorry, things got busy but this is now complete.
