### ISSUE TITLE
Ruby 2.3 syntax

### ISSUE THREAD

**Issue by isaacfreeman** [boomerdigital/solidus_avatax_certified#82]
In the v1.0-v2.0 branch, the gemspec specifies Ruby version >=2.1.

However, app/models/solidus_avatax_certified/line.rb uses the safe navigation operator &. that was introduced in Ruby 2.3.
https://github.com/boomerdigital/solidus_avatax_certified/blob/v1.0-v2.0/app/models/solidus_avatax_certified/line.rb#L159

Possible solutions:
1. Replace the `&.` with a `try(...)`
2. Bump up the required Ruby version to 2.3

**Comment by dhonig** [comment]
Thanks Isaac.   I'd say that the simplest thing is to bump up the gem version, but perhaps may clients of this gem aren't ready to make that leap?  Do you want to send us a PR for the try version?   I think it will serve the community better to go with option 1 ( though I like option 2 better)
