### ISSUE TITLE
Sandbox documentation warning

### ISSUE THREAD

**Issue by prwhitehead** [boomerdigital/solidus_avatax_certified#94]
I'm new to Avatax and did not understand from your documentation (or the Avatax developer docs) that a seperate sandbox account is required before the gem will work in development. Adding a line at the top of the setup wiki would potentially save another developer from spending an entire morning trying to understand what is going on as they build their knowledge of the service and your gem. 

Thanks for all the time you've invested in this, I'm sure when the client sets up the Sandbox account, I'll very much appreciate it.

**Comment by acreilly** [comment]
Sure thing! You can use your production credentials, but you will be charged per document commit.
https://github.com/boomerdigital/solidus_avatax_certified/wiki

**Comment by prwhitehead** [comment]
Thanks for replying. 

I think the issue I had was that `:production` and `:sandbox` environment states were hard coded depending on the Rails env. This means I had to go into the gem and comment out code in order to use the production account and make the gem work. If you allowed the environment to be set from an initializer it could make the entire process a lot simpler. :)
