### ISSUE TITLE
All Preferences lost when server restarts

### ISSUE THREAD

**Issue by prwhitehead** [boomerdigital/solidus_avatax_certified#95]
I'd very much like to use the gem for a site already in production, however all preferences are lost when the server restarts, address, countries, boolean values. 

    solidus (2.4.2)
      solidus_api (= 2.4.2)
      solidus_backend (= 2.4.2)
      solidus_core (= 2.4.2)
      solidus_frontend (= 2.4.2)
      solidus_sample (= 2.4.2)

    solidus_avatax_certified (3.1.0)
     avatax-ruby
     json (~> 1.8)
	 logging (~> 2.0)
	 solidus_core (>= 2.3.0, < 3.0.0)
	 solidus_support

**Comment by askl56** [comment]
@prwhitehead In the meantime did you find a way of using this in production?

**Comment by prwhitehead** [comment]
Hello, 

I have the following in my ENV file - the values have been removed for security: 

# Avatax Tax information
AVATAX_ACCOUNT=
AVATAX_LICENSE_KEY=
AVATAX_COMPANY_CODE=

Am I missing anything?

**Comment by acreilly** [comment]
Nope, that is it. If you look in the gem's config/initializers you will see a file called avatax.rb. This is where the env is set. Looks like this:

`
Spree::Avatax::Config.account = ENV['AVATAX_ACCOUNT'] if ENV['AVATAX_ACCOUNT']
Spree::Avatax::Config.license_key = ENV['AVATAX_LICENSE_KEY'] if ENV['AVATAX_LICENSE_KEY']
Spree::Avatax::Config.company_code = ENV['AVATAX_COMPANY_CODE'] if ENV['AVATAX_COMPANY_CODE']
`

**Comment by prwhitehead** [comment]
Thank you for confirming. 

So it works for the most part, however I cannot change any settings or restart my ruby server or the values not stored in the ENV file will be lost.

**Comment by askl56** [comment]
@acreilly Why is there not a fallback to set this stuff in `secrets.yml` or something?

**Comment by skukx** [comment]
@prwhitehead If you are working in development and make a change, anything in the `/initializers` folder will not be reloaded. This could be the cause of preferences not appearing. This won't happen in production.

**Comment by skukx** [comment]
This doesn't sound like an issue with the gem then.  Are you sure your environment variables are being loaded when rails is started?

**Comment by prwhitehead** [comment]
There is admin panel, where the details you enter are not propagated to the database but instead stored in memory, so when a deployment is performed (restarting the server process), or in development when the server is restarted, the details from the admin control panel are lost and need to be reentered.

**Comment by dhonig** [comment]
@prwhitehead  that sounds like a misunderstanding.  I think the reason is that they we have moved to support 12Factor.    Storing keys in the database was an old pattern with Spree that has fallen out of favor over time. Can you set the keys in the environment and let us know if that resolves the issue.   The fact you have to re-enter these in production means this isn't a viable production deployment as it stands.    @acreilly

**Comment by prwhitehead** [comment]
Once again I’d like to state how grateful I am for the work done creating this gem, it saved me a lot of time. 

The issue I had using it was there are no docs apart from the wiki and the wiki Setup Requirments only references the admin panel and how to setup the gem using it. There is no mention of the environment variables, nor that the admin panel is obsolete. 

As someone with zero knowledge regarding Avatax or the gem before being tasked with implementing an integration, I found this very confusing. Once I realised it wasn’t required integration was an hour, but I spent 3 days trying to work out wahat was causing the issues I was seeing.

**Comment by dhonig** [comment]
Appreciated. Its been a few years/evolutions in the making.  Sounds like we should file a github issue to ammend the wiki and make sure instructions are provided to save others from falling into the pitfall?

**Comment by skukx** [comment]
@dhonig Since environment configuration has become the standard. Is there a need for an admin panel anymore? Or possibly keep the admin panel but mark all fields as readonly to avoid confusion?

**Comment by dhonig** [comment]
@skukx  whatever we think is more straightforward.  To me that would be removing the fields and updating the documentation as part of the release.

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_avatax_certified/wiki
