### ISSUE TITLE
Incorrect country title

### ISSUE THREAD

**Issue by prwhitehead** [boomerdigital/solidus_avatax_certified#97]
The default set for "address_validation_enabled_countries" option uses "United States", but Solidus uses "United States of America"

https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/spree/avatax_configuration.rb#L8

So the the option not selected in the control panel.

**Comment by acreilly** [comment]
```
=> #<Spree::Country id: 233, iso_name: "UNITED STATES", iso: "US", iso3: "USA", name: "United States", numcode: 840, states_required: true, updated_at: nil, created_at: nil>
```

**Comment by acreilly** [comment]
Older versions did, but it has been a serveral versions since the change.
